function createAlarm() { var alarmSound = new Audio('../audio/alarm.mp3'); alarmSound.loop = true; return alarmSound; };
var alarm = createAlarm();
var walkText = document.getElementById('walk');
var gotitButton = document.getElementById('gotit');
var clock = document.getElementById('clock');
function startAlarm() { alarm.play(); walkText.style.visibility = 'visible'; return gotitButton.disabled = false; };
function stopAlarm() { alarm.pause(); walkText.style.visibility = 'hidden'; return gotitButton.disabled = true; };
function padZero(x) { return x < 10 ? '0' + x : x; };
function formatTime(hours, minutes, seconds) { return padZero(hours) + ':' + padZero(minutes) + ':' + padZero(seconds); };
function updateTime() { var now = new Date(); var hours = now.getHours(); var minutes = now.getMinutes(); var seconds = now.getSeconds(); var currentTime = formatTime(hours, minutes, seconds); clock.innerHTML = currentTime; return 0 === minutes && 0 === seconds ? startAlarm() : null; };
updateTime();
setInterval(updateTime, 1000);
